# Generated by Django 5.2.7 on 2025-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_events_app', '0004_alter_usersubmission_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
